name: Deploy to Docker Hub

# Chạy quy trình này khi có code push lên nhánh main
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Action lấy code từ Github
    - name: Checkout
      uses: actions/checkout@v4

    # 2. Action Đăng nhập Docker Hub (sử dụng Secrets đã tạo ở Bước 1)
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Action Đóng gói & Đẩy Image (Sử dụng tags như yêu cầu)
    - name: Build and push Docker images
      uses: docker/build-push-action@v7
      with:
        context: .
        push: true
        # Thay 'xinchaodocker' bằng tên repository bạn vừa tạo trên Docker Hub
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/xinchaodocker:latest
